In [9]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

We are going to create a function that provides us all the games in each region for the 2021/2022 season of Championnat National 3.

In [10]:
def get_matches_poules(poule): # User provides the name of the groupe with a letter corresponding to a region.
    
    h_teams = []
    a_teams = []
    scores = []
    no_journee = []
    for i in range(1,27): # Teams play 26 games in a season
        r = requests.get(f'https://www.bienpublic.com/sport/calendrier-resultats/football/national-national-3-groupe-{poule}/{i}')
        soup = BeautifulSoup(r.text, 'html.parser')

        
        for j in range(len(soup.select('td.scoreData'))):
            home_team = soup.select('td.firstTeam a')[j].get_text() # Home Team
            away_team = soup.select('td.secondTeam a')[j].get_text() # Away Team
            score = soup.select('td.scoreData')[j].get_text().strip() # Score
            
            h_teams.append(home_team)
            a_teams.append(away_team)
            scores.append(score)
            no_journee.append(i)
            

    
    df = pd.DataFrame(data = {'Equipe_Dom': h_teams,
                             'Equipe_Ext': a_teams,
                             'Score': scores,
                             'Journee': no_journee,
                              'Region': poule})
    
    df.to_csv(f'poule_{poule}.csv') # Export a dataframe of the region with all the games played during the season.

In [11]:
def get_matches_poules_corse(poule): # User provides the name of the groupe with a letter corresponding to a region.
    
    h_teams = []
    a_teams = []
    scores = []
    no_journee = []
    for i in range(1,29): # Teams play 26 games in a season
        r = requests.get(f'https://www.bienpublic.com/sport/calendrier-resultats/football/national-national-3-groupe-{poule}/{i}')
        soup = BeautifulSoup(r.text, 'html.parser')

        
        for j in range(len(soup.select('td.scoreData'))):
            home_team = soup.select('td.firstTeam a')[j].get_text() # Home Team
            away_team = soup.select('td.secondTeam a')[j].get_text() # Away Team
            score = soup.select('td.scoreData')[j].get_text().strip() # Score
            
            h_teams.append(home_team)
            a_teams.append(away_team)
            scores.append(score)
            no_journee.append(i)
            

    
    df = pd.DataFrame(data = {'Equipe_Dom': h_teams,
                             'Equipe_Ext': a_teams,
                             'Score': scores,
                             'Journee': no_journee,
                              'Region': poule})
    
    df.to_csv(f'poule_{poule}.csv') # Export a dataframe of the region with all the games played during the season.

In [12]:
import time
t1 = time.time()
get_matches_poules('a')
get_matches_poules('b')
get_matches_poules('c')
#get_matches_poules('d')
get_matches_poules('e')
get_matches_poules('f')
get_matches_poules('h')
get_matches_poules('i')
get_matches_poules('j')
get_matches_poules('k')
get_matches_poules('l')
get_matches_poules('m')
t2 = time.time()
t = t2 - t1
print(f'Temps d éxécution : {time.strftime("%M: %S", time.gmtime(t))}')

Temps d éxécution : 03: 24

In [13]:
get_matches_poules_corse('d')

In [18]:
df = pd.concat([pd.read_csv('poule_a.csv'),
               pd.read_csv('poule_b.csv'),
               pd.read_csv('poule_c.csv'),
               pd.read_csv('poule_d.csv'),
               pd.read_csv('poule_e.csv'),
               pd.read_csv('poule_f.csv'),
               pd.read_csv('poule_h.csv'),
               pd.read_csv('poule_i.csv'),
               pd.read_csv('poule_j.csv'),
               pd.read_csv('poule_k.csv'),
               pd.read_csv('poule_l.csv'),
               pd.read_csv('poule_m.csv')])
# Here we create a single dataset with all the games.

In [19]:
df

     Unnamed: 0        Equipe_Dom         Equipe_Ext  Score  Journee Region
0             0           Bayonne    Lège-Cap-Ferret  1 - 0        1      a
1             1        Bordeaux 2      Châtellerault  1 - 0        1      a
2             2         Bressuire          Chauvigny  1 - 1        1      a
3             3          Neuville          Tartas Sy  3 - 0        1      a
4             4            Cognac           Libourne  1 - 4        1      a
..          ...               ...                ...    ...      ...    ...
177         177  Bourgoin-Jailleu           Chambéry  0 - 4       26      m
178         178     Haut lyonnais     Vaulx-en-Velin  4 - 2       26      m
179         179    Lyon Duchère 2           Limonest  0 - 2       26      m
180         180           Moulins          Montluçon  2 - 3       26      m
181         181          Velay FC  Saint-Étienne (2)  3 - 3       26      m

[2198 rows x 6 columns]

We then replace the letter in the column region by the name of the region for each game to make it clearer for the analysis.

In [20]:
region_code = {'a': 'Nouvelle Aquitaine',
              'b': 'Pays de la Loire',
              'c': 'Centre',
              'd': 'Corse-Medit',
              'e':'Bourg-Fr Comté',
              'f':'Grand est',
              'h':'Occitanie',
              'i':'Hauts de France',
              'j':'Normandie',
              'k':'Bretagne',
              'l':'Paris IDF',
              'm':'Auvergne Rh Alpes'}

df['Region'].replace(region_code, inplace = True)

In [21]:
df.to_csv('games_national3.csv')